### ISSUE TITLE
Fix the overloads that accept CssBuilder to call Build()

### ISSUE THREAD

**Issue by SQL-MisterMagoo** [EdCharbeneau/CssBuilder#2]
In case Build() is modified to do more than call ToString(), these methods should call Build() in preference to ToString().

```
public CssBuilder AddClass(CssBuilder builder, bool when = true) => when ? this.AddClass(builder.ToString()) : this;

public CssBuilder AddClass(CssBuilder builder, Func<bool> when = null) => this.AddClass(builder.ToString(), when());

```

**Comment by EdCharbeneau** [comment]
ToString and Build should always do the same thing. The reason I added a Build method was to give some semantic meaning to unwrap the stringbuffer. Ideally this should be the same as ToString because Razor can call the ToString method directly and the output needs to be the same.

I'll merge your pull request and see if there's some way to make this more maintainable on the CssBuilder side of the code.
